### ISSUE TITLE
Do we need to register ? 

### ISSUE THREAD

**Issue by Cubey0** [DiSSCo/kb#4]
Could we use ORCID ?
https://info.orcid.org/documentation/integration-guide/

**Comment by juliapim** [comment]
@Cubey0 You don't need to register for now.  If you want to have a look behind the scenes I can create an account for you. The registration is not available because we want to avoid to merge too many local accounts with existing accounts in an SSO based approach such as ORCID. And thank you for the documentation.

**Comment by Cubey0** [comment]
Works for me (& no I don't need an account) - just fussy at issue-reporting when no email appeared.
